services:
  app:
    container_name: zentrix-node
    working_dir: /var/www/html
    image: node:18.7.0
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/var/www/html
    command: sh -c "npm install && npm run build && npm start"

  mongo:
    container_name: zentrix-mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test

volumes:
  mongo-data: